var formdataMatch = {
    "customerName": "非黑即白",
    "customerPhone": "2656865",
    "installationAddress": "回家刚刚好",
    "projectLocal": "该喝喝斤斤计较斤斤计较",
    "reportTime": "2025-05-23 16:20:14",
    "productCode": "哈哈哈姐姐啾啾啾啾啾啾",
    "unitModel": "包不包含",
    "controlProgramVersion": "混混",
    "touchscreenProgramVersion": "",
    "expansionValveControllerVersion": "",
    "productSn": "白白嫩嫩",
    "powerSupply": "叭叭叭",
    "factoryTime": "2025-05-01",
    "debugTime": "2025-05-31",
    "projectCode": "亲戚",
    "projectName": "嗯嗯",
    "debugModel": "亲戚",
    "unitAppearanceDamage": "无",
    "partsDamage": "无",
    "insulationDamage": "无",
    "other": "刚好",
    "isSeparateWiring": "无",
    "isCabinetCleanedMicro": "无",
    "isCabinetCleanedStart": "有",
    "isWiringCompliant": "有",
    "controlPowerConnectionStatus": "异常",
    "relayStatus": "正常",
    "contactorStatus": "异常",
    "powerWiringStatus": "异常",
    "startCabinetGroundingStatus": "异常",
    "lowVoltageInsulationResistance": "观后感",
    "guidePageSwitchStatus": "异常",
    "factoryStatus": "不带氟出厂",
    "airTightnessTestStatus": "异常",
    "prePressureHoldingAirTightness": "风格",
    "postPressureHoldingAirTightness": "",
    "vacuumTestStatus": "异常",
    "prePressureHoldingVacuum": "",
    "postPressureHoldingVacuum": "",
    "refrigerantChargeAmount": "刚刚",
    "refrigerantChargeAmountRadio": "带氟出厂",
    "singlePointLeakRate": "宇",
    "isImpurityInContainer": "否",
    "flowProtectionType": "压差",
    "coolingSideStatus": "异常",
    "freezingSideStatus": "异常",
    "chilledWaterPumpForm": "并联",
    "chilledWaterPumpFlow": "222",
    "chilledWaterPumpHead": "333",
    "coolingWaterPumpForm": "并联",
    "coolingWaterPumpFlow": "55",
    "coolingWaterPumpHead": "66",
    "coolingTowerForm": "开式",
    "coolingTowerFlow": "55",
    "coolingTowerHead": "333",
    "chilledWaterPH": "22",
    "chilledWaterConductivity": "22",
    "isChilledWaterClear": "是",
    "coolingWaterPH": "22",
    "coolingWaterConductivity": "233",
    "isCoolingWaterClear": "否",
    "evaporationPressureLowAlarm": "正常",
    "condensationPressureHighAlarm": "正常",
    "windingTemperatureHighAlarm": "异常",
    "startupTimeExceedAlarm": "异常",
    "gatewayType": "水机博士",
    "networkStatus": "信号弱/无信号",
    "gatewayFixedVersion": "好好",
    "isSetParamsSameAsFactory": "否",
    "specificParams": "",
    "waterControl": "进水控制",
    "coolingHeatingTargetTemp": "55",
    "evaporatorActualControlTemp": "12",
    "exitPauseTempDiff": "22",
    "enterPauseTempDiff": "22",
    "capacityAdjustmentKeepTempDiff": "41",
    "coolingTowerFanAdjustTempDiff": "33",
    "coolingTowerFan1SwitchTemp": "55",
    "coolingTowerFan2SwitchTemp": "26",
    "baudRate": "115200",
    "stationAddress": "",
    "parityBit": "",
    "exitPauseTemperatureDifference": "23",
    "enterPauseTemperatureDifference": "333",
    "controlMode": "定时",
    "operationMode": "制热",
    "ratedCurrent": "565",
    "ratedFrequency": "12",
    "currentTransmitterRange": "22",
    "pressureSensorUpperLimit": "33",
    "evaporatorTargetLiquidLevel": "22",
    "coolingFullLoadPower": "23",
    "iceStorageFullLoadPower": "233",
    "compressorShutdownInterval": "2",
    "startupInterval": "2",
    "quickStartSignalDelay": "",
    "inverter1SoftwareVersion": "更好",
    "inverter2SoftwareVersion": "哈哈哈",
    "inverter3SoftwareVersion": "好纠结",
    "compressor1Version": "一样",
    "maglev1Version": "贴贴",
    "compressor2Version": "回家姐姐",
    "maglev2Version": "",
    "compressor3Version": "",
    "maglev3Version": "",
    "compressor1AZ": "11",
    "compressor1FX": "22",
    "compressor1FY": "22",
    "compressor1RX": "33",
    "compressor1RY": "23",
    "compressor2AZ": "33",
    "compressor2FX": "33",
    "compressor2FY": "66",
    "compressor2RX": "33",
    "compressor2RY": "66",
    "compressor3AZ": "33",
    "compressor3FX": "5",
    "compressor3FY": "67",
    "compressor3RX": "74",
    "compressor3RY": "9",
    "logTime1": "2025-05-16",
    "chilledWaterInletTemp1": "95",
    "chilledWaterOutletTemp1": "89",
    "coolingWaterInletTemp1": "41",
    "coolingWaterOutletTemp1": "99",
    "evaporatorEvaporationPressure1": "2",
    "evaporatorSaturationTemp1": "29",
    "evaporatorTerminalTempDiff1": "36",
    "condenserCondensationPressure1": "46",
    "condenserSaturationTemp1": "4",
    "condenserTerminalTempDiff1": "40",
    "guideVane1Opening1": "70",
    "guideVane2Opening1": "70",
    "guideVane3Opening1": "45",
    "currentPercentage1": "18",
    "logTime2": "2025-05-29",
    "chilledWaterInletTemp2": "19",
    "chilledWaterOutletTemp2": "18",
    "coolingWaterInletTemp2": "6",
    "coolingWaterOutletTemp2": "66",
    "evaporatorEvaporationPressure2": "50",
    "evaporatorSaturationTemp2": "43",
    "evaporatorTerminalTempDiff2": "0",
    "condenserCondensationPressure2": "78",
    "condenserSaturationTemp2": "35",
    "condenserTerminalTempDiff2": "61",
    "guideVane1Opening2": "59",
    "guideVane2Opening2": "29",
    "guideVane3Opening2": "5",
    "currentPercentage2": "38",
    "logTime3": "2025-05-23",
    "chilledWaterInletTemp3": "66",
    "chilledWaterOutletTemp3": "0",
    "coolingWaterInletTemp3": "54",
    "coolingWaterOutletTemp3": "73",
    "evaporatorEvaporationPressure3": "82",
    "evaporatorSaturationTemp3": "5",
    "evaporatorTerminalTempDiff3": "34",
    "condenserCondensationPressure3": "46",
    "condenserSaturationTemp3": "1",
    "condenserTerminalTempDiff3": "37",
    "guideVane1Opening3": "22",
    "guideVane2Opening3": "57",
    "guideVane3Opening3": "5",
    "currentPercentage3": "47",
    "logTime4": "2025-05-23",
    "chilledWaterInletTemp4": "5",
    "chilledWaterOutletTemp4": "33",
    "coolingWaterInletTemp4": "81",
    "coolingWaterOutletTemp4": "9",
    "evaporatorEvaporationPressure4": "8",
    "evaporatorSaturationTemp4": "38",
    "evaporatorTerminalTempDiff4": "48",
    "condenserCondensationPressure4": "50",
    "condenserSaturationTemp4": "87",
    "condenserTerminalTempDiff4": "98",
    "guideVane1Opening4": "56",
    "guideVane2Opening4": "96",
    "guideVane3Opening4": "97",
    "currentPercentage4": "39",
    "logTime5": "2025-05-23",
    "chilledWaterInletTemp5": "51",
    "chilledWaterOutletTemp5": "22",
    "coolingWaterInletTemp5": "73",
    "coolingWaterOutletTemp5": "3",
    "evaporatorEvaporationPressure5": "21",
    "evaporatorSaturationTemp5": "58",
    "evaporatorTerminalTempDiff5": "20",
    "condenserCondensationPressure5": "85",
    "condenserSaturationTemp5": "35",
    "condenserTerminalTempDiff5": "55",
    "guideVane1Opening5": "32",
    "guideVane2Opening5": "6",
    "guideVane3Opening5": "87",
    "currentPercentage5": "74",
    "logTime6": "2025-05-23",
    "chilledWaterInletTemp6": "58",
    "chilledWaterOutletTemp6": "57",
    "coolingWaterInletTemp6": "50",
    "coolingWaterOutletTemp6": "49",
    "evaporatorEvaporationPressure6": "81",
    "evaporatorSaturationTemp6": "68",
    "evaporatorTerminalTempDiff6": "48",
    "condenserCondensationPressure6": "71",
    "condenserSaturationTemp6": "32",
    "condenserTerminalTempDiff6": "7",
    "guideVane1Opening6": "79",
    "guideVane2Opening6": "16",
    "guideVane3Opening6": "99",
    "currentPercentage6": "38",
    "customerTargetTemperature": "56",
    "userSideSupplyVoltagePhase1": "66",
    "userSideSupplyVoltagePhase2": "6",
    "userSideSupplyVoltagePhase3": "5",
    "chilledWaterInletOutletPressureDifference": "3",
    "coolingWaterInletOutletPressureDifference": "6",
    "unitVibrationNoiseCheck": "无异常震动，无异响",
    "fluorideSideFilterTemperatureDifference": "5",
    "userFeedback": "由净乙男命重滤此铸站没米准满验故运官推曾感特猛补湖完氯附涂横。长革击束喊否擦式衡病健钟最曾岁叫雌亚投铸斯究最结警日个镜频长——拌适堂能着落对甘际边您朝泡横赵择值赫含宋兵喊壮杨风伦写慢塘柴；炭我兵含线歌专脸役钱启捕焦勒为根制哲功史他五原花延今懂载呈需？规健叶符望柬新罪讯战柳机颗常新出尖影颗省也托球弧狠浆分仁转猛…亦瓦隙章条耳济条励存凝苏最讲煤吹江优格重被源坚课镜继孙倒标庄——露别愿进浅抢原传决曾宜趋释府质加脸铸省端突耕告灌住塑届洛豆早；企遇浆汽莫欧托以土员含闪世忠些线强俘吸荒采米淡羊业皇锤插从朗？例否者再容逆渠枪池高乡类妇托令区嘴布忽器体首炉打养快蒋泡故儿。津赞向龙全怎优量凡席讯茶占信回遍故顾黑下类亦粪她您天决位恐反。",
    "onSiteTrainingEffect": "由净乙男命重滤此铸站没米准满验故运官推曾感特猛补湖完氯附涂横。长革击束喊否擦式衡病健钟最曾岁叫雌亚投铸斯究最结警日个镜频长——拌适堂能着落对甘际边您朝泡横赵择值赫含宋兵喊壮杨风伦写慢塘柴；炭我兵含线歌专脸役钱启捕焦勒为根制哲功史他五原花延今懂载呈需？规健叶符望柬新罪讯战柳机颗常新出尖影颗省也托球弧狠浆分仁转猛…亦瓦隙章条耳济条励存凝苏最讲煤吹江优格重被源坚课镜继孙倒标庄——露别愿进浅抢原传决曾宜趋释府质加脸铸省端突耕告灌住塑届洛豆早；企遇浆汽莫欧托以土员含闪世忠些线强俘吸荒采米淡羊业皇锤插从朗？例否者再容逆渠枪池高乡类妇托令区嘴布忽器体首炉打养快蒋泡故儿。津赞向龙全怎优量凡席讯茶占信回遍故顾黑下类亦粪她您天决位恐反。",
    "problemsAndSolutions": "不好就不vvv",
    "preStartupCheckStatus": "正常",
    "preStartupCheckDetails": "由净乙男命重滤此铸站没米准满验故运官推曾感特猛补湖完氯附涂横。长革击束喊否擦式衡病健钟最曾岁叫雌亚投铸斯究最结警日个镜频长——拌适堂能着落对甘际边您朝泡横赵择值赫含宋兵喊壮杨风伦写慢塘柴；炭我兵含线歌专脸役钱启捕焦勒为根制哲功史他五原花延今懂载呈需？规健叶符望柬新罪讯战柳机颗常新出尖影颗省也托球弧狠浆分仁转猛…亦瓦隙章条耳济条励存凝苏最讲煤吹江优格重被源坚课镜继孙倒标庄——露别愿进浅抢原传决曾宜趋释府质加脸铸省端突耕告灌住塑届洛豆早；企遇浆汽莫欧托以土员含闪世忠些线强俘吸荒采米淡羊业皇锤插从朗？例否者再容逆渠枪池高乡类妇托令区嘴布忽器体首炉打养快蒋泡故儿。津赞向龙全怎优量凡席讯茶占信回遍故顾黑下类亦粪她您天决位恐反。",
    "operationStatus": "正常",
    "operationDetails": "由净乙男命重滤此铸站没米准满验故运官推曾感特猛补湖完氯附涂横。长革击束喊否擦式衡病健钟最曾岁叫雌亚投铸斯究最结警日个镜频长——拌适堂能着落对甘际边您朝泡横赵择值赫含宋兵喊壮杨风伦写慢塘柴；炭我兵含线歌专脸役钱启捕焦勒为根制哲功史他五原花延今懂载呈需？规健叶符望柬新罪讯战柳机颗常新出尖影颗省也托球弧狠浆分仁转猛…亦瓦隙章条耳济条励存凝苏最讲煤吹江优格重被源坚课镜继孙倒标庄——露别愿进浅抢原传决曾宜趋释府质加脸铸省端突耕告灌住塑届洛豆早；企遇浆汽莫欧托以土员含闪世忠些线强俘吸荒采米淡羊业皇锤插从朗？例否者再容逆渠枪池高乡类妇托令区嘴布忽器体首炉打养快蒋泡故儿。津赞向龙全怎优量凡席讯茶占信回遍故顾黑下类亦粪她您天决位恐反。",
    "otherMatters": "由净乙男命重滤此铸站没米准满验故运官推曾感特猛补湖完氯附涂横。长革击束喊否擦式衡病健钟最曾岁叫雌亚投铸斯究最结警日个镜频长——拌适堂能着落对甘际边您朝泡横赵择值赫含宋兵喊壮杨风伦写慢塘柴；炭我兵含线歌专脸役钱启捕焦勒为根制哲功史他五原花延今懂载呈需？规健叶符望柬新罪讯战柳机颗常新出尖影颗省也托球弧狠浆分仁转猛…亦瓦隙章条耳济条励存凝苏最讲煤吹江优格重被源坚课镜继孙倒标庄——露别愿进浅抢原传决曾宜趋释府质加脸铸省端突耕告灌住塑届洛豆早；企遇浆汽莫欧托以土员含闪世忠些线强俘吸荒采米淡羊业皇锤插从朗？例否者再容逆渠枪池高乡类妇托令区嘴布忽器体首炉打养快蒋泡故儿。津赞向龙全怎优量凡席讯茶占信回遍故顾黑下类亦粪她您天决位恐反。",
    "mideaServicePersonName": "刚刚",
    "mideaServicePersonPhone": "11111111",
    "mideaServiceSignatureDate": "2025-05-22",
    "mideaServiceSignature": "",
    "customerRepresentativeName": "古古怪怪",
    "customerRepresentativePhone": "655",
    "customerSignatureDate": "2025-05-17",
    "customerSignature": ""
}


function generateChineseText(length = 300) {
    // 常用汉字集合
    const chars = '的一是在不了有和人这中大为上个国我以要他时来用们生到作地于出就分对成会可主发年动同工也能下过子说产种面而方后多定行学法所民得经十三之进着等部度家电力里如水化高自二理起小物现实加量都两体制机当使点从业本去把性好应开它合还因由其些然前外天政四日那社义事平形相全表间样与关各重新线内数正心反你明看原又么利比或但质气第向道命此变条只没结解问意建月公无系军很情者最立代想已通并提直题党程展五果料象员革位入常文总次品式活设及管特件长求老头基资边流路级少图山统接知较将组见计别她手角期根论运农指几九区强放决西被干做必战先回则任取据处队南给色光门即保治北造百规热领七海口东导器压志世金增争济阶油思术极交受联什认六共权收证改清己美再采转更单风切打白教速花带安场身车例真务具万每目至达走积示议声报斗完类八离华名确才科张信马节话米整空元况今集温传土许步群广石记需段研界拉林律叫且究观越织装影算低持音众书布复容儿须际商非验连断深难近矿千周委素技备半办青省列习响约支般史感劳便团往酸历市克何除消构府称太准精值号率族维划选标写存候毛亲快效斯院查江型眼王按格养易置派层片始却专状育厂京识适属圆包火住调满县局照参红细引听该铁价严首底液官德调随病苏失尔死讲配女黄推显谈罪神艺呢席含企望密批营项防举球英氧势告李台落木帮轮破亚师围注远字材排供河态封另施减树溶怎止案言士均武固叶鱼波视仅费紧爱左章早朝害续轻服试食充兵源判护司足某练差致板田降黑犯负击范继兴似余坚曲输修的故城夫够送笔船占右财吃富春职觉汉画功巴跟虽杂飞检吸助升阳互初创抗考投坏策古径换未跑留钢曾端责站简述钱副尽帝射草冲承独令限阿宣环双请超微让控州良轴找否纪益依优顶础载倒房突跳章仁区豹贸类何歪利倍俄遍判恐壶拿扩伤飞露核缘游振操央伍域甚迅辉异序免纸夜乡久隶缸夹念兰映沟乙吗儒杀汽磷艰晶插埃燃欢铁补咱芽永瓦倾阵碳演威附牙芽永瓦斜灌欧献顺猪洋腐请透司危括脉宜笑若尾束壮暴企菜穗楚汉愈绿拖牛份染既秋遍锻玉夏疗尖殖井费州访吹荣铜沿替滚客召旱悟刺脑措贯藏敢令隙炉壳硫煤迎铸粘探临薄旬善福纵择礼愿伏残雷延烟句纯渐耕跑泽慢栽鲁赤繁境潮横掉锥希池败船假亮谓托伙哲怀割摆贡呈劲财仪沉炼麻罪祖息车穿货销齐鼠抽画饲龙库守筑房歌寒喜哥洗蚀废纳腹乎录镜妇恶脂庄擦险赞钟摇典柄辩竹谷卖乱虚桥奥伯赶垂途额壁网截野遗静谋弄挂课镇妄盛耐援扎虑键归符庆聚绕摩忙舞遇索顾胶羊湖钉仁音迹碎伸灯避泛亡答勇频皇柳哈揭甘诺概宪浓岛袭谁洪谢炮浇斑讯懂灵蛋闭孩释乳巨徒私银伊景坦累匀霉杜乐勒隔弯绩招绍胡呼痛峰零柴簧午跳居尚丁秦稍追梁折耗碱殊岗挖氏刃剧堆赫荷胸衡勤膜篇登驻案刊秧缓凸役剪川雪链渔啦脸户洛孢勃盟买杨宗焦赛旗滤硅炭股坐蒸凝竟陷枪黎救冒暗洞犯筒您宋弧爆谬涂味津臂障褐陆啊健尊豆拔莫抵桑坡缝警挑污冰柬嘴啥饭塑寄赵喊垫丹渡耳刨虎笔稀昆浪萨茶滴浅拥穴覆伦娘吨浸袖珠雌妈紫戏塔锤震岁貌洁剖牢锋疑霸闪埔猛诉刷狠忽灾闹乔唐漏闻沈熔氯荒茎男凡抢像浆旁玻亦忠唱蒙予纷捕锁尤乘乌智淡允叛畜俘摸锈扫毕璃宝芯爷鉴秘净蒋钙肩腾枯抛轨堂拌爸循诱祝励肯酒绳穷塘燥泡袋朗喂铝软渠颗惯贸粪综墙趋彼届墨碍启逆卸航衣孙龄岭骗休借'

    let text = ''
    while (text.length < length) {
        const char = chars.charAt(Math.floor(Math.random() * chars.length))
        text += char
    }

    // 简单的句子划分和标点处理
    let result = ''
    const sentences = Math.ceil(text.length / 30) // 每30字左右一句
    const avgLength = Math.floor(text.length / sentences)

    for (let i = 0; i < sentences; i++) {
        let start = i * avgLength
        let end = (i === sentences - 1) ? text.length : (i + 1) * avgLength

        // 随机选择标点符号
        let punctuation = ['。', '！', '？', '；', '…', '——']
        let punct = punctuation[Math.floor(Math.random() * punctuation.length)]

        // 确保最后一个字符是标点
        if (i < sentences - 1) {
            result += text.substring(start, end) + punct
        } else {
            result += text.substring(start, end) + '。'
        }
    }

    return result
}
